# Importing libraries and Datasets

In [54]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Splitting the dataset

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler_test = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler_test.fit_transform(X_test)

In [57]:
X_train[0:6]

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255]])

In [58]:
X_test[0:6]

array([[ 0.75872215, -1.41078892],
       [ 1.9109871 ,  0.5590031 ],
       [-0.83672162, -0.75419158],
       [ 0.93599368,  0.79776576],
       [-0.74808586, -1.23171691],
       [-0.65945009, -0.21697557]])

# Training the logistic regression on the TRAINING SET 

In [59]:
from sklearn.linear_model import LogisticRegression
classifier  = LogisticRegression(random_state = 42, C = 1.0)
classifier.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=42, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

# Predicting a new result 

In [60]:
print(classifier.predict(scaler.transform([[30, 87000]])))

[0]


# Predicting For TEST SET 

In [61]:
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

In [62]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[61  2]
 [12 25]]


# MODEL SCORE

In [63]:
print(classifier.score(X_test, y_test) * 100, '%')

86.0 %
